name: Récupérer le Code Source et Exécuter sous Windows

on:
  push:
    branches:
      - main

jobs:
  retrieve-code:
    runs-on: windows-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Afficher le contenu du dossier
      run: |
        Get-ChildItem -Recurse
